//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance
    {
        public int ID_Journey { get; set; }
        public int ID_Borrower { get; set; }
        public int ID_Lender { get; set; }
        public Nullable<decimal> Advance_Money { get; set; }
        public Nullable<int> Is_Active { get; set; }
    
        public virtual Journey Journey { get; set; }
        public virtual JourneyAttendance JourneyAttendance { get; set; }
        public virtual JourneyAttendance JourneyAttendance1 { get; set; }

        //For Binding
        public string Borrower_Name { get; set; }
        public string Lender_Name { get; set; }
        public string Money_For_Binding { get; set; }
        public int Advance_Index { get; set; }
    }
}
