//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journey()
        {
            this.Advances = new HashSet<Advance>();
            this.Expenses = new HashSet<Expens>();
            this.JourneyAttendances = new HashSet<JourneyAttendance>();
            this.JourneyImages = new HashSet<JourneyImage>();
            this.Routes = new HashSet<Route>();
        }
    
        public int ID_Journey { get; set; }
        public string Journey_Name { get; set; }
        public Nullable<int> ID_Site { get; set; }
        public string Start_Place { get; set; }
        public string Start_Province { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> Distance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advance> Advances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expens> Expenses { get; set; }
        public virtual Site Site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JourneyAttendance> JourneyAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JourneyImage> JourneyImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }

        //For Binding
        public string Site_Name { get; set; }
        public string Site_Avatar { get; set; }
        public double Journey_Progress { get; set; }
        public int Total_Day { get; set; }
        public int Total_Member { get; set; }
        public string Total_Day_For_Binding { get; set; }
        public string Total_Member_For_Binding { get; set; }
        public string Total_Distance_For_Binding { get; set; }
        public string Start_Date_For_Binding { get; set; }
        public string End_Date_For_Binding { get; set; }
        public List<Route> Route_For_Binding { get; set; }
        public List<JourneyAttendance> Members_For_Binding { get; set; }
        public List<JourneyImage> Images_For_Binding { get; set; }
        public List<DevideMoney_Result> Devide_Money_For_Binding { get; set; }
        public decimal Total_Receivables { get; set; }
        public string Total_Receivables_For_Binding { get; set; }
        public decimal Total_Expenses { get; set; }
        public string Total_Expenses_For_Binding { get; set; }
        public decimal Remain { get; set; }
        public string Remain_For_Binding { get; set; }
    }
}
