//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.Generic;
    
    public partial class JourneyAttendance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JourneyAttendance()
        {
            this.Advances = new HashSet<Advance>();
            this.Advances1 = new HashSet<Advance>();
        }
    
        public int ID_Member { get; set; }
        public int ID_Journey { get; set; }
        public string Member_Name { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<decimal> Receivables_Money { get; set; }
        public string Role { get; set; }
        public Nullable<int> Is_Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advance> Advances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advance> Advances1 { get; set; }
        public virtual Journey Journey { get; set; }
    }
}
