//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.Generic;
    
    public partial class JourneyAttendance
    {
        public int ID_Member { get; set; }
        public int ID_Journey { get; set; }
        public Nullable<decimal> Receivables_Money { get; set; }
        public string Role { get; set; }
    
        public virtual Journey Journey { get; set; }
        public virtual Member Member { get; set; }
    }
}
