//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeSplit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string about_us_page_name {
            get {
                return ResourceManager.GetString("about_us_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Site.
        /// </summary>
        public static string add_site_page {
            get {
                return ResourceManager.GetString("add_site_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help_page_name {
            get {
                return ResourceManager.GetString("help_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search your journey by name and member....
        /// </summary>
        public static string hint_text_search {
            get {
                return ResourceManager.GetString("hint_text_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home_page_name {
            get {
                return ResourceManager.GetString("home_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage journeys.
        /// </summary>
        public static string manage_journey_page {
            get {
                return ResourceManager.GetString("manage_journey_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hiển thị Splash Screen khi khởi chạy ứng dụng vào lần tới..
        /// </summary>
        public static string message_not_show_splash {
            get {
                return ResourceManager.GetString("message_not_show_splash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string text_all {
            get {
                return ResourceManager.GetString("text_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chuyến đi hiện tại.
        /// </summary>
        public static string text_cur_journey {
            get {
                return ResourceManager.GetString("text_cur_journey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chuyến đi đã thực hiện.
        /// </summary>
        public static string text_done_journey {
            get {
                return ResourceManager.GetString("text_done_journey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string text_filter {
            get {
                return ResourceManager.GetString("text_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-Z.
        /// </summary>
        public static string text_item_sort_az {
            get {
                return ResourceManager.GetString("text_item_sort_az", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string text_item_sort_end_date {
            get {
                return ResourceManager.GetString("text_item_sort_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string text_item_sort_route {
            get {
                return ResourceManager.GetString("text_item_sort_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string text_item_sort_start_date {
            get {
                return ResourceManager.GetString("text_item_sort_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string text_item_sort_status {
            get {
                return ResourceManager.GetString("text_item_sort_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-A.
        /// </summary>
        public static string text_item_sort_za {
            get {
                return ResourceManager.GetString("text_item_sort_za", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chuyến đi sắp tới.
        /// </summary>
        public static string text_planed_journey {
            get {
                return ResourceManager.GetString("text_planed_journey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all journeys.
        /// </summary>
        public static string text_view_all_journey {
            get {
                return ResourceManager.GetString("text_view_all_journey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW DETAIL.
        /// </summary>
        public static string text_view_detail {
            get {
                return ResourceManager.GetString("text_view_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string tip_close_window_button {
            get {
                return ResourceManager.GetString("tip_close_window_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string tip_maximize_window_button {
            get {
                return ResourceManager.GetString("tip_maximize_window_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string tip_minimize_window_button {
            get {
                return ResourceManager.GetString("tip_minimize_window_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string tip_next_page {
            get {
                return ResourceManager.GetString("tip_next_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string tip_previous_page {
            get {
                return ResourceManager.GetString("tip_previous_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore down.
        /// </summary>
        public static string tip_restore_window_button {
            get {
                return ResourceManager.GetString("tip_restore_window_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string title_sort_box {
            get {
                return ResourceManager.GetString("title_sort_box", resourceCulture);
            }
        }
    }
}
